### ISSUE TITLE
COMMENTS WANTED: Stretch Goals Idea Thread

### ISSUE THREAD

**Issue by jakeherold** [jakeherold/ajj#8]
Which things are we excited about? How can we improve functionality?

**Comment by jakeherold** [comment]
Advanced//manual entry for MPG

**Comment by jakeherold** [comment]
Isn't there a requirement for multiple pages? What can we do to make it have several sections?
1. About Devs Page
2. About your car: mileage/gas guzzler status/other interesting stats presented well?
3. Thank-you page//popup for the api's we're using?
4. link to spotify playlist of roadtrip music?

**Comment by jakeherold** [comment]
oops. closed on accident

**Comment by jakeherold** [comment]
Fastest route vs senic route

**Comment by jakeherold** [comment]
get walking distance, and switch mpg to miles per burger or someting similar

**Comment by jessicahur** [comment]
I think we've got enough on our plate as for now so I'll close this today. We can totally re-open it tomorrow if we meet our goals today/tomorrow :)
